#ifndef GOENGC_SIZE_H
#define GOENGC_SIZE_H

#define GOENGC_MAX_BOARD_SIZE 19
#define GOENGC_PAD 1
#define GOENGC_DATA_SIZE (GOENGC_MAX_BOARD_SIZE + 2 * GOENGC_PAD)
#define GOENGC_DATA_SIZE_SQUARED (GOENGC_DATA_SIZE * GOENGC_DATA_SIZE)

#endif /* GOENGC_SIZE_H */
